name: firstapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
#  flutter_native_splash: "^2.2.17"
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_launcher_icons: "^0.11.0"
  animated_splash_screen:

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
#flutter_native_splash:
#  color: "#42a5f5"
#  image: assets/images/fly.png
#  android_gravity: fill